### ISSUE TITLE
ColorPicker doesn't work (Linux/Arch/Sublime Text 2)

### ISSUE THREAD

**Issue by Spheerys** [weslly/ColorPicker#31]
Hi !

I can't launch ColorPicker.
When I try, I have this on the log :

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./ColorPick.py", line 40, in run
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 1139, in _execute_child
OSError: [Errno 8] Erreur de format pour exec()
```

Any idea ?

**Comment by nusher87** [comment]
Thank you!  This solved my problem : )
