### ISSUE TITLE
ColorPicker throws [Errno 13] Permission denied

### ISSUE THREAD

**Issue by sebastianschnock** [weslly/ColorPicker#68]
Hi there,
since today (was working fine before) the following error pops up in the console when I try to open the color picker:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/home/basti/.config/sublime-text-3/Packages/ColorPicker/sublimecp.py", line 354, in run
    color = cp.pick(self.view.window(), selected)
  File "/home/basti/.config/sublime-text-3/Packages/ColorPicker/sublimecp.py", line 309, in pick
    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
```

OS: Ubuntu 14.04
Sublime Text 3 Build 3065
ColorPicker v.1.11.0

**Comment by facelessuser** [comment]
That is probably my fault.  I simplified the initial setup, but I forgot to chmod the Linux script.  In the plugin directory, if you chmod the Linux script under lib, it should work again.  I'll push a fix today. Sorry.

**Comment by weslly** [comment]
Fixed :)

**Comment by facelessuser** [comment]
Thanks!
