### ISSUE TITLE
Don't run ColorPicker, Windows XP, Sublime Text 3

### ISSUE THREAD

**Issue by Kristinita** [weslly/ColorPicker#81]
```
Traceback (most recent call last):
  File "D:\Сублим\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 365, in run
    color = cp.pick(self.view.window(), selected)
  File "C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 316, in pick
    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
OSError: [WinError 193] %1 не является приложением Win32

```

**Comment by Kristinita** [comment]
Not reproduced last time for me. Closed.
