### ISSUE TITLE
Color picker not working

### ISSUE THREAD

**Issue by PedroFumero** [weslly/ColorPicker#90]
I'm pressing ``ctrl + shift + c`` but nothing shows up, also try enter with ``ctrl + shift + p`` and typing Color Picker, but nothing happens.

After to hit command to run color picker, console shows me the next:

> Traceback (most recent call last):
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
>     return self.run(edit)
>   File "C:\Users\Pedro\AppData\Roaming\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 365, in run
>     color = cp.pick(self.view.window(), selected)
>   File "C:\Users\Pedro\AppData\Roaming\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 316, in pick
>     proc = subprocess.Popen(args, stdout=subprocess.PIPE)
>   File "./python3.3/subprocess.py", line 784, in __init__
>   File "./python3.3/subprocess.py", line 980, in _get_handles
>   File "./python3.3/subprocess.py", line 1030, in _make_inheritable
> OSError: [WinError 6] Controlador no válido

I'm using sublime text 3 with Windows 7

**Comment by miprogrammer** [comment]
No longer working for me either on windows 7

**Comment by miprogrammer** [comment]
Found some weird behavior. I open sublime text by passing a folder in on the command line. I have several links to different folders depending on what project I am working on.

When I open sublime text this way, colorpicker doesn't work.

If I open the regular way and then open the folder, it works. So there is an issue with the startup passing a folder

**Comment by williamcanin** [comment]
I have the same problem. Has anyone found a solution?

=================
Linux Fedora 27
Sublime Text 3 (3143)

**Comment by jesteves** [comment]
@williamcanin (Not to be rude with @weslly, but...) since I _really_ needed the functionality and unfortunately this issue is not solved yet (I'm on Sublime Text 3.1.1 @ macOS) I decided to give [ColorPick](https://packagecontrol.io/packages/ColorPick) a try, and It can be used as an alternative IMHO.

P.S.  For what it's worth: before writing this I just tried uninstalling and reinstalling ColorPicker several times without success.  It's almost like it was silently not being installed: no warnings con console, but no function whatsoever...

**Comment by ultraUser76** [comment]
Hi. 
I have read/google it a lot and can't find a solution.

ctrl + shift + c not working . 
Ubuntu 18.04

Is this plugin still maintained? Saw that the las commit was a long time ago.
Thanks.
